"use client";

import React from "react";
import { LegalLayout } from "@/components/legal/LegalLayout";
import { AlertCircle, ShieldAlert, Cpu, FileCheck } from "lucide-react";

export default function DisclaimerPage() {
  return (
    <LegalLayout
      title="Legal Disclaimer"
      subtitle="Operational Liability Limits, High-Risk Automation & Third-Party System Disclaimers."
      lastUpdated="September 24, 2026"
    >
      <div className="space-y-6">
        <section className="space-y-3">
          <h2 className="text-xl font-bold text-[#1B1B1B] tracking-tight flex items-center gap-2">
            <AlertCircle className="w-5 h-5 text-[#874436]" />
            1. Automated Execution & High-Risk Operational Disclaimers
          </h2>
          <p>
            FlowMesh is an automated workflow orchestration platform capable of executing arbitrary database DML mutations, financial payment dispatches (e.g., Stripe, SAP ERP, Banking Ledgers), and webhook triggers.
          </p>
          <div className="bg-[#FAF8F5] border border-[#D5CABE] rounded-xl p-4 text-xs text-[#5C5C5C] leading-relaxed">
            <strong>CUSTOMER OPERATIONAL RESPONSIBILITY:</strong> You are exclusively responsible for auditing, simulating, and validating the business logic of your Directed Acyclic Graphs (DAGs) prior to production deployment. FlowMesh, its architects, and its contributors assume zero liability for erroneous ledger transfers, unintended data truncations, or cascading downstream outages caused by misconfigured workflow parameters.
          </div>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-[#1B1B1B] tracking-tight flex items-center gap-2">
            <Cpu className="w-5 h-5 text-[#874436]" />
            2. Third-Party Connector Trademarks & Integrations
          </h2>
          <p>
            All third-party product names, logos, and brands referenced throughout FlowMesh (including but not limited to SAP, Oracle, Stripe, PostgreSQL, Redis, Apache Kafka, NATS, and Kubernetes) are the property of their respective trademark owners.
          </p>
          <p className="text-xs text-[#5C5C5C]">
            Reference to these trademarks does not imply endorsement, affiliation, sponsorship, or official certification by the trademark holders. FlowMesh implements connectors using public APIs, open database wire protocols, and standard RFC specifications.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-[#1B1B1B] tracking-tight flex items-center gap-2">
            <ShieldAlert className="w-5 h-5 text-[#874436]" />
            3. No Financial, Legal, or Tax Advisory
          </h2>
          <p>
            Information generated by FlowMesh diagnostics, audit logs, and ledger reconciliation summaries does not constitute formal financial accounting, tax advice, or regulatory compliance counsel. Organizations must perform their own independent audits in accordance with GAAP, IFRS, or regional banking directives.
          </p>
        </section>

        <section className="space-y-3 pt-4 border-t border-[#EAE2D8]">
          <span className="text-xs font-semibold text-[#1B1B1B] block">Legal & Governance Clarifications:</span>
          <p className="text-xs text-[#5C5C5C]">
            Direct all inquiries regarding liability boundaries or commercial indemnity riders to:{" "}
            <a href="mailto:ashutosh4tech@gmail.com" className="font-mono font-bold text-[#874436] hover:underline">
              ashutosh4tech@gmail.com
            </a>
          </p>
        </section>
      </div>
    </LegalLayout>
  );
}
