"use client";

import React from "react";
import { LegalLayout } from "@/components/legal/LegalLayout";
import { Lock, Shield, Key, FileCheck, CheckCircle2 } from "lucide-react";

export default function SecurityPolicyPage() {
  return (
    <LegalLayout
      title="Enterprise Security Policy"
      subtitle="Cryptographic Architecture, STRIDE Threat Mitigation & Zero-Trust Posture."
      lastUpdated="September 24, 2026"
    >
      <div className="space-y-6">
        <section className="space-y-3">
          <h2 className="text-xl font-bold text-[#1B1B1B] tracking-tight flex items-center gap-2">
            <Lock className="w-5 h-5 text-[#874436]" />
            1. Zero-Trust Security Philosophy
          </h2>
          <p>
            FlowMesh is engineered on the assumption that enterprise corporate networks are hostile and cloud providers cannot be trusted with raw database credentials or ERP records. Every layer of FlowMesh—from our Go Edge Agent to our FastAPI control plane and Spring Boot enterprise workers—implements mutual authentication, ephemeral key derivation, and signed execution contracts.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-[#1B1B1B] tracking-tight flex items-center gap-2">
            <Key className="w-5 h-5 text-[#874436]" />
            2. Cryptographic Envelope Encryption
          </h2>
          <div className="bg-[#FAF8F5] border border-[#D5CABE] rounded-2xl p-5 space-y-3">
            <p className="text-xs text-[#5C5C5C] leading-relaxed">
              Connection credentials are never persisted in plaintext. We implement a two-tier key hierarchy:
            </p>
            <ul className="text-xs text-[#5C5C5C] space-y-2 list-disc pl-5">
              <li>
                <strong>Key Encryption Key (KEK):</strong> A 256-bit master key held exclusively in customer infrastructure (HashiCorp Vault, AWS KMS, or hardware HSM).
              </li>
              <li>
                <strong>Data Encryption Key (DEK):</strong> Ephemeral per-tenant encryption keys derived dynamically using AES-256-GCM with authenticated associated data (AAD).
              </li>
              <li>
                <strong>Ed25519 Signatures:</strong> Edge Agent task invocations must bear valid cryptographic signatures generated by the control plane before local dispatch is permitted.
              </li>
            </ul>
          </div>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-[#1B1B1B] tracking-tight flex items-center gap-2">
            <Shield className="w-5 h-5 text-[#874436]" />
            3. STRIDE Threat Model Mitigations
          </h2>
          <div className="overflow-x-auto rounded-xl border border-[#D5CABE]">
            <table className="w-full text-left text-xs">
              <thead className="bg-[#F4EFEB] border-b border-[#D5CABE] text-[#1B1B1B] font-bold">
                <tr>
                  <th className="p-3">Threat (STRIDE)</th>
                  <th className="p-3">FlowMesh Architectural Mitigation</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#EAE2D8] text-[#5C5C5C]">
                <tr>
                  <td className="p-3 font-semibold text-[#1B1B1B]">Spoofing Identity</td>
                  <td className="p-3">Mutual TLS (mTLS) with client certificate verification for all edge daemons.</td>
                </tr>
                <tr>
                  <td className="p-3 font-semibold text-[#1B1B1B]">Tampering with Data</td>
                  <td className="p-3">Ed25519 cryptographic payload signing; tamper-evident append-only audit trail.</td>
                </tr>
                <tr>
                  <td className="p-3 font-semibold text-[#1B1B1B]">Repudiation</td>
                  <td className="p-3">Immutable audit logs with tenant and actor correlation recorded via AuditLoggingService.</td>
                </tr>
                <tr>
                  <td className="p-3 font-semibold text-[#1B1B1B]">Information Disclosure</td>
                  <td className="p-3">Zero-inbound firewall requirement (ADR-0001); client-side data plane execution.</td>
                </tr>
                <tr>
                  <td className="p-3 font-semibold text-[#1B1B1B]">Denial of Service</td>
                  <td className="p-3">LockFreeTokenBucketRateLimiter and bounded thread pool CallerRunsPolicy backpressure.</td>
                </tr>
                <tr>
                  <td className="p-3 font-semibold text-[#1B1B1B]">Elevation of Privilege</td>
                  <td className="p-3">No arbitrary code execution (ADR-0002); least-privilege RBAC role enforcement.</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        <section className="space-y-3 pt-4 border-t border-[#EAE2D8]">
          <span className="text-xs font-semibold text-[#1B1B1B] block">Security Leadership & Vulnerability Inquiries:</span>
          <p className="text-xs text-[#5C5C5C]">
            Direct all questions or requests for SOC 2 Type II reports to our security lead:{" "}
            <a href="mailto:ashutosh4tech@gmail.com" className="font-mono font-bold text-[#874436] hover:underline">
              ashutosh4tech@gmail.com
            </a>
          </p>
        </section>
      </div>
    </LegalLayout>
  );
}
