global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "flowmesh-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api:8000", "host.docker.internal:8000"]
        labels:
          environment: "production"
          plane: "control-plane"

  - job_name: "flowmesh-enterprise-worker"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["enterprise-worker:8082", "host.docker.internal:8082"]
        labels:
          environment: "production"
          service: "enterprise-worker"
          stack: "jvm-spring-boot"
